export const divStyles = {
  outerDiv: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundSize: '100% 105%',
    color: 'white',
    height: '100%',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: '30px',
    background: 'url(https://i.imgur.com/lKSF2O0.png)',
    fontFamily: 'sans',
  },
  innerDiv1: {
    display: 'flex',
    height: '33%',
  },
  innerDiv2: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    height: '33%',
    fontWeight: '700',
    fontSize: '45px',
  },
  innerDiv3: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    height: '33%',
    fontWeight: '700',
    fontSize: '30px',
  },
};
