name: Build and Deploy
on:
  push:
    branches:
      - main
      - ipfs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0

      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build

      - name: IPFS Deploy 🚀
        uses: aquiladev/ipfs-action@v1.0.0
        with:
          path: ./build
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}

      - name: IPFS (Pinata)
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
